Manually doing TF-IDF: https://towardsdatascience.com/natural-language-processing-feature-engineering-using-tf-idf-e8b9d00e7e76

In [20]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt

%matplotlib inline
# 시각화 결과가 선명하게 표시되도록
%config InlineBackend.figure_format = 'retina'

In [21]:
df = pd.read_csv("combined_wrangling_db.csv")
df.shape

(100, 248)

In [22]:
df.head()

,PTfreq,PT관련명사,PTfreq.1,PT관련서술어,PTfreq.2,PT관련명사.1,PTfreq.3,PT관련서술어.1,검도freq,검도관련명사,...,핫요가freq.1,핫요가관련서술어,헬스freq,헬스관련명사,헬스freq.1,헬스관련서술어,힙레freq,힙레관련명사,힙레freq.1,힙레관련서술어
0,263,운동,13,많은,263,운동,13,많은,2051,검도,...,238,좋아요,1306,운동,110,좋아요,747,힙,76,열리는
1,164,헬스,13,좋아요,164,헬스,13,좋아요,596,운동,...,202,아쉬,953,헬스,107,챌,710,발레,46,자세한
2,102,다이어트,12,들,102,다이어트,12,들,522,검,...,73,다양한,336,다이어트,54,좋은,478,운동,42,이어
3,83,필라테스,9,해서,83,필라테스,9,해서,451,도관,...,69,소소한,270,팔,53,좋,464,포레스티,40,바꿀
4,64,니스,9,좋은,64,니스,9,좋은,232,동검,...,58,들,263,필라테스,47,하면,452,벌,38,되는

In [23]:
df['힙레관련명사']

0        힙
1       발레
2       운동
3     포레스티
4        벌
      ...
95      추천
96      먼스
97       잇
98      영리
99     캠페인
Name: 힙레관련명사, Length: 100, dtype: object

In [26]:
bagOfWordsA = df['힙레관련명사'].to_list()
print(bagOfWordsA)
len(bagOfWordsA)

['힙', '발레', '운동', '포레스티', '벌', '꼬끄', '르', '시티', '핏', '니스', '웰', '레', '서울숲', '힙합', '바', '글로벌', '취미', '무용', '요가', '데이', '줌', '댄스', '티켓', '육아', '필라테스', '파티', '일상', '한국', '클래스', '하루', '맘', '캣츠', '골든', '여자', '홍대', '부기', '오프닝', '가희', '티', '프로그램', '데일리', '포스팅', '뷰티', '스', '브', '서울', '워커힐', '램', '포르', '공연', '크루', '오리지널', '비스타', '트레이닝', '나', '다이어트', '토요일', '애', '소통', '예매', '내용', '가든', '번', '숲', '참여', '츄', '춤', '라이브', '톡', '코리아', '주말', '이벤트', '시카고', '홈', '호텔', '벤트', '댓글', '바디', '호머', '드', '페스티벌', '당신', '아트', '키네시스', '싱잉', '인생', '아래', '우먼', '중', '이후', '육', '피트', '씨', '명', '슬로건', '추천', '먼스', '잇', '영리', '캠페인']

100

In [27]:
bagOfWordsB = df['살사관련명사'].to_list()
print(bagOfWordsB)
len(bagOfWordsB)

['살사', '바차타', '댄스', '라틴', '동호회', '홍대', '취미', '여행', '수업', '강습', '쿠바', '강남', '운동', '춤', '클럽', '소셜', '다이어트', '영어', '파티', '공연', '텐션', '활동', '파타야', '쌤', '바', '정모', '방콕', '키', '좀바', '맛집', '모임', '시간', '클래스', '일상', '오사카', '오픈', '직장', '수원', '나', '커플', '일본', '것', '사진', '중', '부산', '초급', '반', '번', '생활', '주차', '핫', '설', '예약', '연말', '에버', '스다', '시시시', '슈얼', '홍', '맘보', '오늘', '크루', '연습', '연휴', '아카데미', '차', '신청', '베이직', '금요일', '토요일', '수요일', '음악', '소통', '주', '시작', '하바나', '이태원', '친구', '속', '플레이스', '미군', '부대', '거', '팔', '감사', '일요일', '중급', '사람', '서울', '여기', '이번', '수강', '댄서', '술', '스터디', '언어', '교환', '한곡', '벨', '남미']

100

In [28]:
uniqueWords = set(bagOfWordsA).union(set(bagOfWordsB))
print(uniqueWords)
len(uniqueWords)

{'싱잉', '소통', '하루', '강습', '동호회', '벌', '모임', '사람', '육', '벨', '프로그램', '이태원', '소셜', '거', '줌', '서울', '시간', '서울숲', '호머', '웰', '당신', '한곡', '티', '오리지널', '맛집', '이벤트', '강남', '쿠바', '비스타', '수원', '시작', '텐션', '댄스', '힙합', '살사', '스', '아래', '캠페인', '설', '여행', '댄서', '차', '슬로건', '맘', '라틴', '초급', '가희', '아카데미', '가든', '캣츠', '여기', '일상', '언어', '춤', '크루', '좀바', '일본', '술', '속', '클래스', '사진', '신청', '쌤', '미군', '티켓', '스다', '연말', '운동', '플레이스', '에버', '발레', '번', '것', '르', '홈', '뷰티', '시티', '하바나', '추천', '홍', '니스', '영어', '트레이닝', '수요일', '한국', '연휴', '바차타', '교환', '음악', '일요일', '친구', '명', '글로벌', '오늘', '톡', '슈얼', '포르', '예매', '핏', '중급', '활동', '파티', '무용', '브', '홍대', '데이', '영리', '요가', '내용', '애', '우먼', '아트', '램', '오프닝', '연습', '중', '바디', '이번', '나', '파타야', '데일리', '바', '키네시스', '생활', '베이직', '페스티벌', '금요일', '반', '힙', '주차', '수업', '부산', '오사카', '팔', '커플', '스터디', '클럽', '공연', '인생', '주', '맘보', '레', '숲', '꼬끄', '포스팅', '다이어트', '피트', '씨', '코리아', '직장', '감사', '워커힐', '드', '먼스', '육아', '참여', '오픈', '방콕', '핫', '키', '골든', '부대', '여자', '남미', '츄', '이후', '수강', '필라테스', '예약', '토요일', '잇', '주말', '취미', '시카고', '벤트', '호텔', '댓글', '라이브', '부기', '포레스티', '정모', '시시시'}

182

In [29]:
numOfWordsA = dict.fromkeys(uniqueWords, 0)
for word in bagOfWordsA:
    numOfWordsA[word] += 1
numOfWordsB = dict.fromkeys(uniqueWords, 0)
for word in bagOfWordsB:
    numOfWordsB[word] += 1

In [30]:
def computeTF(wordDict, bagOfWords):
    tfDict = {}
    bagOfWordsCount = len(bagOfWords)
    for word, count in wordDict.items():
        tfDict[word] = count / float(bagOfWordsCount)
    return tfDict

In [31]:
tfA = computeTF(numOfWordsA, bagOfWordsA)
tfB = computeTF(numOfWordsB, bagOfWordsB)

In [32]:
def computeIDF(documents):
    import math
    N = len(documents)
    
    idfDict = dict.fromkeys(documents[0].keys(), 0)
    for document in documents:
        for word, val in document.items():
            if val > 0:
                idfDict[word] += 1
    
    for word, val in idfDict.items():
        idfDict[word] = math.log(N / float(val))
    return idfDict

In [33]:
idfs = computeIDF([numOfWordsA, numOfWordsB])

In [34]:
def computeTFIDF(tfBagOfWords, idfs):
    tfidf = {}
    for word, val in tfBagOfWords.items():
        tfidf[word] = val * idfs[word]
    return tfidf

In [35]:
tfidfA = computeTFIDF(tfA, idfs)
tfidfB = computeTFIDF(tfB, idfs)
df_result = pd.DataFrame([tfidfA, tfidfB])

In [36]:
df_result

,싱잉,소통,하루,강습,동호회,벌,모임,사람,육,벨,...,취미,시카고,벤트,호텔,댓글,라이브,부기,포레스티,정모,시시시
0,0.006931,0.0,0.006931,0.000000,0.000000,0.006931,0.000000,0.000000,0.006931,0.000000,...,0.0,0.006931,0.006931,0.006931,0.006931,0.006931,0.006931,0.006931,0.000000,0.000000
1,0.000000,0.0,0.000000,0.006931,0.006931,0.000000,0.006931,0.006931,0.000000,0.006931,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.006931,0.006931

In [37]:
# 0이 키네시스, 1가 차바타
# 높은 순으로 정렬을 했다는 것은 바차타에는 없고(=0), 키네시스에는 있다는 것(=0.69)
df_result.T.sort_values(by=0, ascending=False).head(60)

             0    1
싱잉    0.006931  0.0
무용    0.006931  0.0
데일리   0.006931  0.0
바디    0.006931  0.0
오프닝   0.006931  0.0
램     0.006931  0.0
아트    0.006931  0.0
우먼    0.006931  0.0
애     0.006931  0.0
내용    0.006931  0.0
요가    0.006931  0.0
영리    0.006931  0.0
데이    0.006931  0.0
브     0.006931  0.0
핏     0.006931  0.0
페스티벌  0.006931  0.0
예매    0.006931  0.0
포르    0.006931  0.0
톡     0.006931  0.0
글로벌   0.006931  0.0
한국    0.006931  0.0
트레이닝  0.006931  0.0
니스    0.006931  0.0
추천    0.006931  0.0
시티    0.006931  0.0
뷰티    0.006931  0.0
홈     0.006931  0.0
르     0.006931  0.0
키네시스  0.006931  0.0
힙     0.006931  0.0
티켓    0.006931  0.0
여자    0.006931  0.0
포레스티  0.006931  0.0
부기    0.006931  0.0
라이브   0.006931  0.0
댓글    0.006931  0.0
호텔    0.006931  0.0
벤트    0.006931  0.0
시카고   0.006931  0.0
주말    0.006931  0.0
잇     0.006931  0.0
필라테스  0.006931  0.0
이후    0.006931  0.0
츄     0.006931  0.0
골든    0.006931  0.0
인생    0.006931  0.0
참여    0.006931  0.0
육아    0.006931  0.0
먼스    0.006931  0.0
드     0.006931  0.0
워커힐   0.006931  0.0
코리아   0.006931  0.0
씨     0.006931  0.0
피트    0.006931  0.0
포스팅   0.006931  0.0
꼬끄    0.006931  0.0
숲     0.006931  0.0
레     0.006931  0.0
발레    0.006931  0.0
명     0.006931  0.0